{
 "title": "Airflow cluster dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "airflow_id", "label": "Airflow Instance Id", "query": "airflow" }
  ]
 },
 "panels": [
  { "title": "Overview – Today", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DAG Success Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(af_agg_dagrun_duration_success{airflow_id=\"$airflow_id\"}[1d]))"
    }
   ]
  },
  {
   "title": "DAG Failed Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  increase(af_agg_dagrun_duration_failed{airflow_id=\"$airflow_id\"}[1d])\n)"
    }
   ]
  },
  {
   "title": "Tasks Failed Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(af_agg_ti_failures{airflow_id=\"$airflow_id\"}[1d])\n)"
    }
   ]
  },
  {
   "title": "Avg DAG Duration Today (sec)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  af_agg_dag_task_duration{airflow_id=\"$airflow_id\", quantile=\"0.5\"}\n)"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_scheduler_heartbeat{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Dagbag size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dagbag_size{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Total DAG parse time today",
   "type": "stat",
   "description": "Total DAG parse time today",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(af_agg_dag_processing_total_parse_time{airflow_id=\"$airflow_id\"}[1d])"
    }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "stat",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dag_processing_import_errors{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Zombies killed",
   "type": "stat",
   "description": "Zombie tasks killed",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_zombies_killed{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Total successful tasks",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_ti_successes{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Operator success rate per minuite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(af_agg_ti_successes{airflow_id=\"$airflow_id\"}[1m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Operator failure rate per minute",
   "type": "timeseries",
   "description": "Total failures of given operator",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(af_agg_ti_failures{airflow_id=\"$airflow_id\"}[1m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Total failed tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_ti_failures{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  { "title": "Executor Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Jobs started per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(af_agg_ti_start{airflow_id=\"$airflow_id\"}[5m]) * 60",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Executor open slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_executor_open_slots{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor queued tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_executor_queued_tasks{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Jobs ended per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(af_agg_ti_finish{airflow_id=\"$airflow_id\"}[1m]) * 60",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Executor running tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_executor_running_tasks{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "DAG stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true
  },
  {
   "title": "Success DAG run duration",
   "type": "timeseries",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "af_agg_dagrun_duration_success{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Failed DAG run duration",
   "type": "timeseries",
   "description": "Seconds taken for a DagRun to reach failed state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "af_agg_dagrun_duration_failed{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "timeseries",
   "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (dag_id) (\n  increase(\n    af_agg_dag_task_duration_sum{airflow_id=\"$airflow_id\"}[1d]\n  )\n)",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run dependency check time",
   "type": "timeseries",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "af_agg_dagrun_dependency_check{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  }
 ]
}